<Project>
    <Import Project="local.props" Condition="Exists('local.props')"/>
    <Import Project="LocalSettings.props" Condition="Exists('LocalSettings.props')"/>
    <Import Project="Sts2PathDiscovery.props" Condition="Exists('Sts2PathDiscovery.props')"/>

    <PropertyGroup>
        <GodotPath Condition="'$(GodotPath)' == ''">D:\222\dark\Godot_v4.5.1-stable_mono_win64\Godot_v4.5.1-stable_mono_win64\Godot_v4.5.1-stable_mono_win64.exe</GodotPath>
        <RitsuLibDeployDir Condition="'$(RitsuLibDeployDir)' == ''">$(ModsPath)STS2-RitsuLib/</RitsuLibDeployDir>
    </PropertyGroup>
</Project>
