# -*- coding: utf-8 -*-
import json, io, re, sys

texts = []
with io.open(r'D:\ManosabaLin\uniq_ancients2.txt', encoding='utf-8-sig') as f:
    content = f.read()
blocks = re.split(r'### \[\d+\] ', content)
for b in blocks:
    if not b.strip():
        continue
    lines = b.split('\n')
    zh_lines = []
    for ln in lines:
        if ln.startswith('  keys:'):
            break
        zh_lines.append(ln)
    zh = '\n'.join(zh_lines).strip()
    if zh:
        texts.append(zh)

print("解析唯一文本数:", len(texts))

eng_translations = [
    "...I understand. I will use it to protect justice, not for you.",
    "[b][sine]Please,[/sine][/b][jitter]save [color=#cccccc]her[/color][/jitter][b][sine], I beg you[/sine][/b]",
    "[b]【Knocked flying by Sherry Tachibana】[/b]\n[jitter]Ugh... such a tiny detective, yet such strength! How fun! It's rare to find a little one who understands me![/jitter]\nThese relics need no exchange—they're a pure gift. Even if you don't love battle, may you have the confidence to face any danger!",
    "[i](Faint, but there is indeed a voice)[/i]",
    "[i][b](Hiro frowns, gripping his longsword) Disgusting[/b][/i]",
    "[jitter][b]Is anyone... able to hear my voice...[/b][/jitter]",
    "[jitter]【Darv laughs heartily】[/jitter]\nI just love sharing my collection! If you find any curious trinkets climbing the tower later, remember to come back and trade new treasures with me",
    "【Acknowledge the pain you created; acknowledge that all things should not be bent to your will】",
    "【Darv rummages through a pile of metal fragments, muttering vaguely】",
    "【Sherry Tachibana keeps sharing the stories she knows】\nHow fun! How fun!",
    "【Natsume Anan steps back half a step, hugging her sketchbook tighter.】 This one is not here to be put on display.",
    "【Natsume Anan stops at a distance, arms firmly wrapped around her sketchbook, deliberately keeping distance to avoid close contact.】",
    "...Boring? This is already my most formal attire",
    "...Um, hello. My name is Sakuraba Emma. I really... don't know how to use weapons well",
    "...Don't you think I'm strange? Running into the tower alone, knowing nothing, always troubling others",
    "...Can I still be forgiven?",
    "...I will come again. Not for a part of you",
    "...A new guest has arrived. Don't worry, these melting parts won't burn you. Please, sit",
    "Ah... you carry a very special aura. Not a creation of the Spire, nor an ordinary mortal. That kind of... cursed power",
    "Ah—Sakuraba Emma. Finally. I have waited for you so, so long. Give yourself to me, and you shall become as feared by all as I am!",
    "Oh dear, your outfit looks a bit dull. Come, let me pick something pretty for you to wear",
    "Oh, a rare guest! Few walk alone into my collection room. Look around, take your pick",
    "Oh, a little writer from afar. You hide yourself in such dark colors, you've nearly crushed that notebook by hugging it so tight.",
    "Hehe~ I'm a bit strong~ Let's try without weapons!",
    "Anan instinctively hugs her sketchbook and steps back half a step. After a long hesitation, she lowers her head to write",
    "Forgotten Guardian",
    "There are many who are stronger than me. Those who can truly help... thank you",
    "Don't wake me... zZZzz...",
    "It's merely a crude work I casually fabricated in my spare time, with a shallow plot unworthy of being seen",
    "Incorrect! Evil! Once I correct the incorrectness atop the tower, I shall burn you, demon!",
    "Overreaching. The vain obsessions of mere mortals cannot shake the will that built this entire world.",
    "Pure power, pure emotion, a useless puppet",
    "Pure evil. One who has only a single emotion is not worth learning from\n【Sherry Tachibana ignores Vakuu, still speaking, and leaves directly】",
    "Witch of the Island",
    "Visitors!! Stories and mysteries! Detective stories!",
    "The tower... too noisy... you go fight... go quell the Architect's twisted correctness",
    "Everyone in the tower chases battle; only you favor words that flee conflict. Truly rare. Take my blessing",
    "Here, here—take these!! Take the shiny things!! It'll warm your heart a little!!",
    "Lonely... want to see light! Want to see victory! Want the bad guys shattered!! Take it! Go fight! I'll watch from here!",
    "Come rest a while; climbing the tower is so tiring...",
    "Haha! Such gloomy fighting spirit! Dare to speak of victory without throwing a punch? Interesting! Take my power and write your story to the very end!",
    "Haha! Interesting! A mighty weakling—use my power to correct everything!",
    "Fine, fine! Delusion, is it? Then let's see how far your ridiculous justice can go!",
    "Hehe, don't be nervous. Beauty belongs not only to clothing—it can also hide within the wishes on the page. Take my blessing, and let your words gain a touch of fortune and luster.",
    "Hehe, you have good taste. You look well-behaved, though your attire is too plain and dull. No matter—since you've come, I shall grant you fortune and splendid blessings.",
    "Good. May the flame be with you... don't let it... consume you...",
    "Good. May your journey be lush with flowers and every card a treasure. Go, for the beauty in your heart",
    "Go find the filling and come back",
    "Continue",
    "The Spire's long road is bitter and cold; slaughter and darkness never cease. I was born of flame, born to spread light.",
    "Using others' lives to settle a personal grudge is nothing but your revenge script",
    "Even if the road ahead is hard, I will not shrink back",
    "Come closer to the fire; let my flame warm you and heal you.",
    "Tired... then stop and rest. The Spire's path is too hard, the wind and snow too cold",
    "Power should not be given so easily... What is your intention?",
    "Traveler, do you crave beauty and fortune? Take my gift and let the tower shine for you",
    "No worries, take your pick! Come again often!",
    "Tiny weaver of lies, you actually climbed to the root of the world.",
    "Take it... a part of me... to bring you peace...",
    "Um, hello. I'm just passing through. Is this... your home?",
    "Then go! Deconstruct every mystery of this tower!",
    "You! You! Climbed so high!! Shiny justice!! Take it! Get stronger!",
    "You don't swing a sword, yet you already judge others! Words are a mighty weapon too!! That dark red one won't fight me either, and neither will you! But you're all interesting!",
    "You're not helping them. You're turning them into puppets. Into more people like yourself. I don't need this kind of help",
    "Your spiritual arts are quite interesting. Very well, choose a blessing as you wish—just don't fall too early on the road",
    "Your power... comes from sacrificing yourself?",
    "Your eyes are clean, pure. My body can grow without limit—no need for pity, no need for sorrow.",
    "You humans are all the same. You enter with flaws, leave with resolve—then return with new flaws. Welcome back",
    "That notebook of yours is filled with dense rows of words—not like the scraps others toss away. A complete story...?",
    "Are you... locking yourself away?",
    "This notebook of yours is full of others' stories, exactly like the story fragments I collect!",
    "Hello there! Your hall is truly beautiful, and you yourself are elegant and noble—the most refined and gentle existence I've seen in the tower.",
    "Source of the distortion, I have come to correct you",
    "Oh? A little one hiding behind the pages. How many times have you written an ending you wished to redo? I can give you a contract, and rewrite all those eyesores.",
    "Oh? Another little one stepping into the hall of contracts. Do you too crave power that leaps to the top in one step, willing to pay any price for a profitable deal with me?",
    "Mighty conviction—go kill that detestable Architect!!",
    "Listen",
    "Puppet, puppet! You actually climbed this high!",
    "If you ever wish, I can sit here quietly and listen to you tell the whole story with your pen!! I'll never urge you to speak!",
    "Weakling! Come fight me! Win, and I shall grant you power!",
    "A rare quiet traveler! Do you fear the power of burning?",
    "Yes... to have a place where one may lie freely and rest without pretense is the greatest fortune in the world...",
    "It is merely the peaceful everyday my pen yearns for—a fantasy entrusted to words...",
    "You speak as if you've already tasted the flavor of falling. Good. I like those who understand the price.",
    "Awaken, distant soul...",
    "Take your pick! As long as you know their worth!",
    "So I will never sign it. If the story is to continue, it cannot rely on stealing others' wills.",
    "Once you step here, there is no turning back",
    "Too weak! Do you lack even the strength to grip a weapon?!",
    "Too weak. A little girl who can't even grip a weapon wants to threaten a demon?!",
    "It sounds like a most tempting deal, but I also know you enjoy watching mortals trapped by desire, torn between choices",
    "Wow, we've reached the top of the tower. Is this the truth of everything!?",
    "Wow, so many relics of unknown origin, how interesting~\nStoring so many treasures—could you be deliberately hiding some key evidence? Like an item that could unravel the tower's truth or the mystery of a sealed room?",
    "I won't sign. Forgiveness isn't something you trade for. Someone like you will never understand—because you don't think anything needs forgiveness",
    "My story? My story isn't very interesting, but I know many stories of others—whether detective novels or things that actually happened~",
    "I will master it, and with this burning justice, illuminate the top of the tower",
    "I will correct everything",
    "I'm Sherry Tachibana, a detective!",
    "I am correctness, I am justice, you unreasonable people",
    "I'm the detective Sherry Tachibana. I apologize for disturbing your rest. Giving your own flesh and blood to strangers time and again—does it hurt? Does it tire you?",
    "I'm the detective Sherry Tachibana. Thank you for sharing your warmth with unknown climbers.",
    "I accept this power. I will correct the Architect, just as I correct my past self",
    "The stories I know have ended.\nHmm~ Isn't your very existence the tower's greatest unsolved mystery? You too are seeking a truth that belongs to you, aren't you?",
    "I ask you to convey to [color=#cccccc]her[/color]... that [color=#cccccc]she[/color] no longer needs to bear that so-called [jitter][b]【fate of being born a witch】[/b][/jitter]",
    "I keep melting. Every day. Every moment. Others think I'm fading—but I'm actually regenerating. The old flows away, the new grows in. It hurts, but this is not a bad thing",
    "I am willing to bear the cost, for my innocent ideal",
    "I wish to trade power for peace and end the chaos here",
    "I only hope [color=#cccccc]she[/color]... can find her own [b]【happiness】[/b] while coexisting with humans",
    "This one is not skilled at fighting. If proof is truly needed, words and schemes can also bring one to ruin.",
    "This one already knows what hollow emptiness rewriting endings through others' hands leaves behind. A contract is just another kind of brainwashing.",
    "This one only wishes to find a secluded corner undisturbed by others to rest a while\n【Anan presses the pen tip hard against the paper】",
    "Forgive yourself first. Those who burn away their flaws have the right to start over",
    "Offer me your prayers, and I shall grant you the power to climb.",
    "The little one has sharp eyes! All beings have obsessions—greed, vengeance, ambition to reach the top—all my best chips. I only need to dangle a little bait, and they'll offer up their own bottom lines. This game never gets old",
    "Thank you. A little lighter, but I walk steadier than before",
    "Thank you... may your road ahead never require pretense, and always be met with gentleness...",
    "A new little one! Come see my collection?!",
    "Learn from me, and find a little peace",
    "Very well, pick a blessing to take with you; the climb is fraught with danger",
    "A noble guest deserves a noble blessing. Little girl, power lies not in what you once did, but in what you now wish to do. Don my power and destroy the madness atop the tower",
    "You seek correctness alone? Then go find the Architect. My collection will always be waiting here for you—!",
    "Another awakened soul... I sense an unusual aura in you. You seem... not afraid at all?",
    "Another climber stepping into the arena! The Spire's slaughter never ends—perfect, come have a fierce bout with me and stretch my limbs!",
    "Another challenger! Don't hide your face in that notebook! Come, pick up a weapon and let me see your courage!",
    "A little one from afar, welcome to my splendid domain.",
    "During your journey, you encountered an ancient being known as the Witch of the Island.",
    "Found it, found it!! This one's ugly... this one's shiny!! But no!! What Orobas seeks is—",
    "A nature so willing to bear the cost for a moment of fleeting pleasure—this one cannot understand",
    "This is incorrect. My enemy is the distortion atop the tower",
    "Is this a rewind? I can feel it again, the distortion atop the tower...",
    "These things, I do not need",
    "Detective... have you come seeking the truth? The secrets hidden in this tower are enough to drive most people mad",
    "A detective's duty is to see every truth that others overlook~",
    "Traveler of justice... power demands a price",
    "Just passing through; I have nothing to offer in exchange",
]

assert len(eng_translations) == len(texts), f"{len(eng_translations)} != {len(texts)}"

mapping = {zh: en for zh, en in zip(texts, eng_translations)}
with io.open(r'D:\ManosabaLin\map_ancients_eng.json', 'w', encoding='utf-8') as f:
    json.dump({"eng/ancients.json": mapping}, f, ensure_ascii=False, indent=2)
print("已生成 map_ancients_eng.json, 条目数:", len(mapping))
